spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nbcam
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

## ???? ??? ???
jwt:
  secret:
    key: 8XGn2hQKPTOFcYuTnulDzom59YnIBsws0rKw1xogQOA=

logging:
  level:
    root: info  # 전체 로그 기본 레발 유지 (error, warn 포함)
    org.hibernate.sql: debug  # SQL 로그
    org.hibernate.orm.jdbc.bind: trace  # 바인딩된 파라미터 출력